export const courseCategories = [
  {
    id: 1,
    title: "Full Stack Development",
    price: "₹15,000 + ₹10,000 placement",
    image: "/full-stack-web-development.png",
    subCourses: [
      "Python Full Stack: Python, Django, React.js, MySQL",
      "MERN Stack: MongoDB, Express.js, React.js, Node.js",
      "MEAN Stack: MongoDB, Express.js, Angular, Node.js",
      "Java Full Stack: Java, Spring Boot, Hibernate, React.js/Angular, MySQL",
      "PHP Full Stack : PHP, Laravel , React.js/Angular, MySQL",
    ],
  },
  {
    id: 2,
    title: "Web Development",
    price: "₹7,000",
    image: "/web_development.webp",
    subCourses: [
      "Frontend Development: HTML, CSS, JavaScript, Bootstrap, React.js",
      "Backend Development: Node.js, Django, PHP, Laravel",
      "WordPress Development",
    ],
  },
  {
    id: 3,
    title: "Blockchain & Web3",
    price: "₹20,000 + ₹10,000 placement",
    image: "/web3.jpeg",
    subCourses: [
      "Blockchain Development: Solidity, Ethereum, Smart Contracts",
      "Web3 & NFT Development",
    ],
  },
  {
    id: 4,
    title: "Data Science & Machine Learning",
    price: "₹20,000 + ₹10,000 placement",
    image: "/machineLearning.jpg",
    subCourses: [
      "Data Science with Python",
      "Machine Learning & AI",
      "Deep Learning with TensorFlow & Keras",
      "Business Analytics",
      "Data Analytics",
    ],
  },
  {
    id: 5,
    title: "Mobile App Development",
    price: "₹20,000 + ₹10,000 placement",
    image: "/mobileAppDevelopment.png",
    subCourses: [
      "Flutter Development",
      "Android Development (Java/Kotlin)",
      "iOS Development (Swift)",
      "React Native Development",
    ],
  },
  {
    id: 6,
    title: "Cyber Security & Ethical Hacking",
    price: "₹20,000 + ₹10,000 placement",
    image: "/ethicalHacking.jpg",
    subCourses: [
      "Ethical Hacking & Penetration Testing",
      "Cyber Security Essentials",
      "Bug Bounty",
    ],
  },
  {
    id: 7,
    title: "UI/UX Design",
    price: "₹10,000 + ₹10,000 placement",
    image: "/ui-ux.jpg",
    subCourses: ["Adobe XD, Figma, Sketch"],
  },
  {
    id: 8,
    title: "DevOps & Cloud Computing",
    price: "₹10,000 + ₹10,000 placement",
    image: "/cloudComputing.jpg",
    subCourses: [
      "AWS Cloud Computing",
      "DevOps (Docker, Kubernetes, Jenkins, Git, CI/CD)",
    ],
  },
  {
    id: 9,
    title: "Game Development",
    price: "₹30,000 + ₹10,000 placement",
    image: "/images.jpeg",
    subCourses: ["Unity Game Development", "Unreal Engine Game Development"],
  },
  {
    id: 10,
    title: "Artificial Intelligence (AI) & Automation",
    price: "₹50,000 + ₹10,000 placement",
    image: "/ai.png",
    subCourses: [
      "AI Full Stack",
      "Chatbot Development (OpenAI, LangChain)",
      "RPA (Robotic Process Automation)",
    ],
  },
  {
    id: 11,
    title: "Software Testing & QA",
    price: "₹10,000 + ₹10,000 placement",
    image: "testing.webp",
    subCourses: [
      "Manual Testing",
      "Automation Testing (Selenium, Cypress, JUnit, PyTest)",
    ],
  },
  {
    id: 12,
    title: "Digital Marketing & SEO",
    image: "/digitalmarketing850.jpg",
    price: "₹15,000 + ₹10,000 placement",
    subCourses: [
      "Digital Marketing",
      "SEO, SEM, and SMM",
      "Google Ads & Facebook Ads",
    ],
  },
  {
    id: 13,
    title: "Database Management",
    price: "₹50,000 placement",
    image: "/db.jpeg",
    subCourses: [
      "SQL (MySQL, PostgreSQL, SQL Server)",
      "NoSQL (MongoDB, Firebase)",
    ],
  },
  {
    id: 14,
    title: "Internship & IT Experience Programs",
    price: "₹10,000 placement",
    image: "/internship.png",
    subCourses: [
      "Live Project Internship",
      "Job-Oriented Training with Experience Certificates",
    ],
  },

  {
    id: 15,
    title: "Robotics",
    image: "/robotics.png",
    price: "₹15,000 + ₹10,000 placement",
    subCourses: ["Advanced Embedded Systems", "IoT and Automation", "Robotics"],
  },
  {
    id: 16,
    title: "Graphics Design",
    image: "/graphic design.jpg",
    price: "₹10,000 + ₹10,000 placement",
    subCourses: [
      "2D Animation",
      "Graphics Design, 3D Animation, Video Editing Course",
      "VFX Courses",
    ],
  },
  {
    id: 17,
    title: "Salesforce Development",
    image: "/salesforce.jpeg",
    price: "₹10,000 + ₹10,000 placement",
    subCourses: [
      "Salesforce Admin",
      "Salesforce Developer",
      "Salesforce Lightning",
      "Salesforce Integration & Deployment",
      "Hands-on Projects & Certification Preparation",
    ],
  },
  {
    id: 18,
    title: "CCNA (Cisco Certified Network Associate)",
    price: "₹10,000 + ₹10,000 placement",
    image: "/CCNA-Certified.jpeg",
    subCourses: [
      "Networking Basics",
      "Routing and Switching",
      "IP Connectivity & Services",
      "Network Security Fundamentals",
      "CCNA Certification Preparation",
    ],
  },
];
